### ISSUE TITLE
adding the home page

### ISSUE THREAD

**Issue by jahnvisahni31** [jahnvisahni31/DesignDeck#10]
**Describe the solution you'd like**
adding the home page ui 
you can take reference from this link:

https://www.figma.com/?gad_source=1&gclid=Cj0KCQjw3vO3BhCqARIsAEWblcA_KzLG7AWgcHdAtSwXzHNstAHa4o-6vxvE98GLYG7pyiOKU8lvSkQaApWYEALw_wcB

**Comment by ananyagoyal1** [comment]
Please Assign this task to me under gssoc-extd24 and hacktoberfest

**Comment by kekubhai** [comment]
@jahnvisahni31 can you please add some images of the figma file you added link of , i don't know why it is not opening. Also I know that it has been assigned but I would like to keep a track after @ananyagoyal1 creates a PR  to check how much has been implemented and what more I can do.  Thanks

**Comment by jahnvisahni31** [comment]
@ananyagoyal1  you need to integrate the changes i did not seen any changes 
please integrate the changes with the updated version of code

**Comment by unknown91tech** [comment]
@jahnvisahni31 I can also work on this issue

**Comment by jahnvisahni31** [comment]
@unknown91tech  you can go ahead with the issue.

**Comment by unknown91tech** [comment]
@jahnvisahni31 does the landing page needs to have authentication buttons too ?

**Comment by unknown91tech** [comment]
@jahnvisahni31 I have raised a pr , could you review it

**Comment by jahnvisahni31** [comment]
done and closed successfully
