### ISSUE TITLE
UI upgradation of FAQ page

### ISSUE THREAD

**Issue by Hemant9808** [jahnvisahni31/DesignDeck#101]
UI of FAQ page is not looking good , I have planed something for this . I will redesign the whole page will match with your current theme .

example :
![Screenshot 2024-10-13 132816](https://github.com/user-attachments/assets/9bd08562-829c-49ee-8961-d442464aade9)

KIndly assign this issue to me, so that i can start working on this @jahnvisahni31

**Comment by jahnvisahni31** [comment]
go ahead @Hemant9808
