### ISSUE TITLE
 Dark Mode/Light Mode Switch Lacks Animation and Design

### ISSUE THREAD

**Issue by Zaki2409** [jahnvisahni31/DesignDeck#102]
**Describe the bug**

The dark mode/light mode switch currently functions but lacks visual feedback and a polished design. This can be confusing and frustrating for users.

**To Reproduce**

1. Visit the DesignDesk website.
2. Observe the dark mode/light mode switch.
3. There is no animation or visual change when switching between modes.

**Expected behavior**
A smooth animation should be present to indicate the mode change. The switch should have a visually appealing design that complements the website's aesthetic.

**Screenshots**
![DD](https://github.com/user-attachments/assets/9c5bce31-c0c7-4c58-8170-fa564a5ce8af)
![DD1](https://github.com/user-attachments/assets/60985fd8-5373-48cd-94ff-9a7817c7a5cf)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser :Brave
 - Version : 1.70.126

**Additional context**
Adding a smooth animation and a more visually appealing design for the dark mode/light mode switch would greatly enhance the user experience and create a more polished and intuitive interface.

Kindly assign this issue to me under Hactoberfest accepted , gssoc-ext and relevant tags.

**Comment by jahnvisahni31** [comment]
NOT VALID
