### ISSUE TITLE
Add Terms of Use (ToU) page to the website

### ISSUE THREAD

**Issue by Zaki2409** [jahnvisahni31/DesignDeck#103]
The Terms of Use (ToU) page is currently not added to this website. I wish to create the whole ToU page to outline the rules and guidelines for using the site.

/Assignee
@jahnvisahni31

**Comment by jahnvisahni31** [comment]
go ahead @Zaki2409

**Comment by Zaki2409** [comment]
on it !!

**Comment by Zaki2409** [comment]
Hi @jahnvisahni31,

Could you please review my pull request for the TOU PAGE section? Your feedback would be appreciated!

Thanks!
