### ISSUE TITLE
Updation in README.md file REQUIRED 

### ISSUE THREAD

**Issue by soham0028** [jahnvisahni31/DesignDeck#104]
Hello @jahnvisahni31 
the current readme file lacks proper structure in terms of : 
1. table of contents 
2. featured in section
3. contributors 
4. forkers and styargazers 
5. back to top button 

Kindly Assign me the issue with hacktoberfest and gssoc-extd labels so i can contribute for those events

**Comment by jahnvisahni31** [comment]
go ahead

**Comment by soham0028** [comment]
thankyou so much will revert back asap
