### ISSUE TITLE
Can design Navbar better

### ISSUE THREAD

**Issue by nafri-codes** [jahnvisahni31/DesignDeck#108]

**Comment by jahnvisahni31** [comment]
please provide what you gonna do exactly

**Comment by nafri-codes** [comment]
![Screenshot_20241015-145139.png](https://github.com/user-attachments/assets/5632f5b1-d010-40c7-bf07-707fc11bd029)

In the mobile view we can change the Navbar with burger menus on right and the logo on the right

**Comment by jahnvisahni31** [comment]
sure do this @nafri-codes
