### ISSUE TITLE
Addition of BackToTop Button | UI Enhancement | Smoth Scrolling on Top with One Click

### ISSUE THREAD

**Issue by Shariq2003** [jahnvisahni31/DesignDeck#110]
**Is your feature request related to a problem? Please describe.**
Yes, adding a BackToTop button enhance the UI and provide a better experience to User.

![image](https://github.com/user-attachments/assets/b3f8d4df-8e47-428e-994e-8be982bec899)

Like this, an upward pointing arrow

**Comment by jahnvisahni31** [comment]
go ahead @Shariq2003

**Comment by Shariq2003** [comment]
@jahnvisahni31 could u please increase the level of this issue
