### ISSUE TITLE
Addition of ProgressBar Showcasing Content and Scrolling Depth | UI Enhancement

### ISSUE THREAD

**Issue by Shariq2003** [jahnvisahni31/DesignDeck#111]
**Is your feature request related to a problem? Please describe.**

I want to add a Scrolling Progress Bar that reflect the depht of page or content left in the webpage.
 Just Like in the GSSOC Website

![image](https://github.com/user-attachments/assets/660be189-64aa-4676-8d93-d17d0a1812bd)

Look at the Top, an orange line.

**Comment by jahnvisahni31** [comment]
go ahead @Shariq2003

**Comment by Shariq2003** [comment]
@jahnvisahni31 mam, its also a level 2 feature, could u please increase

![image](https://github.com/user-attachments/assets/b8b6b05b-37a1-4c3d-8b77-5e787195b945)
