### ISSUE TITLE
Customisation of Webpage ScrollBar That match with the Website Theme

### ISSUE THREAD

**Issue by Shariq2003** [jahnvisahni31/DesignDeck#112]
From this

![image](https://github.com/user-attachments/assets/3907d27f-367e-42f4-a1e3-ba704374adc4)

To something like this, that match with the website theme.

![image](https://github.com/user-attachments/assets/0733e166-7b72-4003-a48f-a2ccf93a8fa0)

**Comment by jahnvisahni31** [comment]
go ahead @Shariq2003
