### ISSUE TITLE
adding back to top button

### ISSUE THREAD

**Issue by itznayan** [jahnvisahni31/DesignDeck#114]
**Is your feature request related to a problem? Please describe.**
     Users may have to scroll through long sections of content, and it becomes frustrating when they have to manually scroll back up to the top of the page. This can negatively impact user experience, especially on pages with a lot of content. The lack of an easy way to quickly return to the top of the page can be inconvenient for users.

Describe the solution you'd like

I would like to implement a floating Back to Top button that becomes visible when users scroll past a certain point on the page. When clicked, this button would smoothly scroll the page back to the top using Framer Motion for a smooth and pleasant transition. The button should be unobtrusive yet visible, and it should fade in and out based on the user's scroll position.

Describe alternatives you've considered

I considered allowing users to scroll manually or including "Back to Top" links in various sections of the content. However, I feel that a floating button provides a more user-friendly and accessible option. I also thought about using pure CSS or JavaScript scroll behaviors but believe Framer Motion offers a more polished and customizable scrolling animation.

**Comment by itznayan** [comment]
please assign this issue to me

**Comment by jahnvisahni31** [comment]
already assigned to someone
