### ISSUE TITLE
custom cursor

### ISSUE THREAD

**Issue by itznayan** [jahnvisahni31/DesignDeck#115]
**Is your feature request related to a problem? Please describe.**
    The default browser cursor feels out of place with the overall design of the landing page. I’m frustrated because it doesn’t 
    align with the branding and design aesthetics, and I believe a custom cursor could help create a more cohesive and 
    immersive user experience.

Describe the solution you'd like
    I would like to implement a custom cursor that fits the visual style of the landing page. This could involve changing the 
    cursor to a more stylized shape or design that matches the site's theme, and adding interactions like hover effects that 
    change its size, color, or animation based on user interaction with clickable elements.

Describe alternatives you've considered

I considered leaving the default cursor unchanged or using basic CSS cursor properties like cursor: pointer. However, I believe that a more tailored, animated custom cursor, designed using Framer Motion or SVG, would better enhance the user experience and fit more naturally with the landing page design.

**Comment by jahnvisahni31** [comment]
go ahead @itznayan
