### ISSUE TITLE
 Implement Login and Signup Functionality

### ISSUE THREAD

**Issue by kekubhai** [jahnvisahni31/DesignDeck#116]
Currently, the system does not have a user authentication mechanism. This prevents users from accessing restricted areas and creating personalized profiles. As a result, the system's functionality is limited, and user engagement may be hindered.

Describe the solution you'd like

We propose implementing a login and signup system that allows users to create accounts, authenticate their identity, and access restricted areas of the application. This will provide users with a more personalized experience and enable the system to offer features that require user authentication.

Describe alternatives you've considered

One alternative would be to implement a guest mode that allows users to access certain features without logging in. However, this would limit the functionality available to users and prevent the collection of valuable user data.

Additional context

The implementation of a login and signup system would require the development of a user database and authentication mechanisms. It would also be necessary to implement security measures to protect user data and prevent unauthorized access.

**Comment by jahnvisahni31** [comment]
someone already working
