### ISSUE TITLE
Add Privacy Policy page to the website

### ISSUE THREAD

**Issue by Zaki2409** [jahnvisahni31/DesignDeck#123]
This website does not presently have a Privacy Policy page added. To place forth the policies and procedures for using the website, I would like to create the entire Privacy Policy page.

example format : 

![DDPP](https://github.com/user-attachments/assets/383f47a4-7696-41d4-875e-f4d1b59507b7)

/Assignee

@jahnvisahni31

**Comment by jahnvisahni31** [comment]
go ahead @Zaki2409

**Comment by powerstone666** [comment]
@Zaki2409 are you still working on it?

**Comment by Zaki2409** [comment]
@powerstone666  Yup!! on it.

**Comment by Zaki2409** [comment]
Hi @jahnvisahni31,

Could you please review my pull request for the Privacy Policy page ? Your feedback would be appreciated!

Thanks!
