### ISSUE TITLE
Fix : Text Visibility on Hover for Sign-Up Button on Homepage

### ISSUE THREAD

**Issue by rudrapratap63** [jahnvisahni31/DesignDeck#132]
**Describe the bug**
When hovering over the "Sign Up" button on the homepage, the text becomes invisible. This affects the user experience, as users cannot see the button label when they hover over it.

**To Reproduce**
1. Go to the homepage.
2. Locate the "Sign Up" button.
3. Hover over the "Sign Up" button.
4. Observe that the text is not visible while hovering.

**Expected behavior**
The text should remain visible and readable when the "Sign Up" button is hovered over.

**Screenshots**
![image](https://github.com/user-attachments/assets/daae1266-f604-411b-9dcd-470b34c290e0)

https://github.com/user-attachments/assets/5eaac7ed-b783-4281-8198-05c658c109fc

**Desktop (please complete the following information):**
 - OS: Window 11
 - Browser : Chrome
 - Version : 23H2

**Comment by powerstone666** [comment]
U can go ahead with it...!

**Comment by rudrapratap63** [comment]
Hello @powerstone666, I'm facing an issue while setting up the project locally. I've added the Liveblock public API, but it's not working. Could you please help me out? I'll provide a screenshot of the error I'm encountering. 

![image](https://github.com/user-attachments/assets/76e8ef05-74f6-4bd1-b27d-a82f3d5d2c38)

**Comment by powerstone666** [comment]
could you share the part of code where u hv integrated API

**Comment by rudrapratap63** [comment]
i added liveblock public api in .env file located in root of project 

![image](https://github.com/user-attachments/assets/79d4c3e6-f407-443e-8224-bc4e4ba1ba6a)

**Comment by jahnvisahni31** [comment]
make it  in .env.local
