### ISSUE TITLE
Making Navbar Responsive 

### ISSUE THREAD

**Issue by dev129** [jahnvisahni31/DesignDeck#135]
#### Description
The current navbar lacks responsiveness and visual appeal, which can detract from the overall user experience on the site. A well-designed, responsive navbar is essential for effective navigation, especially on mobile devices.

#### Proposed Solution
I propose to redesign the navbar to be both responsive and visually appealing, aligning it with the site's branding.

#### Plan
1. **Labeling**: Please assign the issue the `GSSOC-ext` and `Hacktoberfest` and `level` labels.
2. **Wireframe**: I will share a wireframe within the first hour of being assigned to the issue.
3. **Approval**: Upon receiving approval for the wireframe, I will start the design process.
4. **Completion**: The design will be completed within 24 hours of wireframe approval.

#### Benefits
- Enhanced user experience through improved navigation on all devices.
- Increased visual appeal, promoting brand consistency.
- Potential for higher user engagement and lower bounce rates.

I look forward to your feedback and hope to contribute positively to the project!

**Comment by powerstone666** [comment]
I'm assigning to you the issue make sure you submit a screenshot or video along with the pull request.
