### ISSUE TITLE
FAQ section is not working

### ISSUE THREAD

**Issue by AswaniBolisetti** [jahnvisahni31/DesignDeck#137]
@jahnvisahni31 
FAQ section is not working, i would like to work on it,
kindly assign this to me

**Comment by powerstone666** [comment]
you can go ahead dont forget to share screenshot or video along with pull request

**Comment by AswaniBolisetti** [comment]
@powerstone666 Sure! but kindly consider it as level 2, i have to work so much on it, so that it gives me motivation

**Comment by AswaniBolisetti** [comment]
@powerstone666 Someone aleardy done with FAQ
