### ISSUE TITLE
Options not visible in light mode

### ISSUE THREAD

**Issue by unknown91tech** [jahnvisahni31/DesignDeck#139]
@jahnvisahni31 The options are not visible in the light mode. Here is a screenshot of the issue

![image](https://github.com/user-attachments/assets/049f25db-0afd-4ce1-a488-ba9fdbb72d33)

Can you assign this to me

**Comment by jahnvisahni31** [comment]
go ahead @unknown91tech

**Comment by unknown91tech** [comment]
@jahnvisahni31 I have created a pr for this , can you check and tell me if there are any changes to be made

**Comment by unknown91tech** [comment]
@powerstone666 @jahnvisahni31 this issue is solved
