### ISSUE TITLE
Adding feedback button

### ISSUE THREAD

**Issue by Aditijainnn** [jahnvisahni31/DesignDeck#148]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

in the fotter or navbar adding feedback/rate-us option so that user can tell there review about the website
aslo in fotter ading github icon in contact us

**Describe alternatives you've considered**

![image](https://github.com/user-attachments/assets/66cddb02-eb89-44fb-974b-50f68f267db1)

assign this to me under gssoc ext and hacktoberfest

**Comment by powerstone666** [comment]
im assigning it to you make sure to resolve all conflicts before requesting a pull request.

**Comment by Aditijainnn** [comment]
> im assigning it to you make sure to resolve all conflicts before requesting a pull request.

ok
