### ISSUE TITLE
[Feature Enhancement] Changing the UI of Terms of Use page to match the UI of the application ✨

### ISSUE THREAD

**Issue by VRtheKing** [jahnvisahni31/DesignDeck#149]
Hii @jahnvisahni31 I wish to totally redesign the UI of our "Terms of Use" page to match the UI of the site, so please assign me this issue under gssoc-ext and hactoberfest level2 so that i can start working immediately.

It requires UI modifications and Original NavBar functionality. And I'd like to implement them.

**Comment by powerstone666** [comment]
k im assigning it to you go ahead make sure to check all conflicts before requesting a pull request by using npm run build or manually.
