### ISSUE TITLE
Create a Contributors page that shows all contributors who worked on develop this application

### ISSUE THREAD

**Issue by yashksaini-coder** [jahnvisahni31/DesignDeck#150]
**Is your feature request related to a problem? Please describe.**
My feature is to add a contributors section that will display all the contributors who worked on developing the website, with their profile picture, no. of time they contributed. Also a nav link that also tells to contribute to the project.

**Describe the solution you'd like**
To fetch the repo data using github API and also using it to grab the contributors id, and writing the functions to scrape the total no. of contributions done by them

**Describe alternatives you've considered**
I have also considered a new feature that can either be add in README doc or into the website itself, It is easy to implement and generate SVG data that needs to be properly showcased

**Additional context**
Add proper labels for `gssoc` & `hacktoberfest`, and assign me this issue. @jahnvisahni31

**Comment by powerstone666** [comment]
go ahead im assigning the issue for you make sure you check for conflicts before requesting a pull request by using npm run build

**Comment by yashksaini-coder** [comment]
> go ahead im assigning the issue for you make sure you check for conflicts before requesting a pull request by using npm run build

are you mentor for this project ?

**Comment by powerstone666** [comment]
yup......!

**Comment by yashksaini-coder** [comment]
> yup......!

got a discord or group for contributors to connect with ?

**Comment by powerstone666** [comment]
No just the general gssoc one........on the discord
