### ISSUE TITLE
Implement_Real-Time_Email_Validation_for_Contact_Form

### ISSUE THREAD

**Issue by smog-root** [jahnvisahni31/DesignDeck#159]
Restricting the "Contact Us" feature to users with email addresses from trusted providers like Gmail or Outlook can have several advantages. Here are some key reasons:

**Spam Reduction:** 

Trusted email providers typically have robust spam filtering mechanisms. By restricting contact to these providers, you can significantly reduce the volume of spam and unwanted inquiries.

**Increased Credibility:**
Emails from established providers are often perceived as more legitimate. This can enhance the credibility of the inquiries received and increase the likelihood of meaningful communication.

_**i'm expecting a gssoc-ext with level3 and a hacktoberfest-accepted label!**_

@jahnvisahni31

**Comment by smog-root** [comment]
@powerstone666 add labels!!

**Comment by smog-root** [comment]
@powerstone666 level1 is too less for it!

**Comment by smog-root** [comment]
add level3 !!

**Comment by powerstone666** [comment]
i guess ur using a npm library to validate which may not be complex so level 1,if I'm wrong correct me with approach ur using I'll change the level.

**Comment by powerstone666** [comment]
max level 2
