### ISSUE TITLE
Notification feature is not there 

### ISSUE THREAD

**Issue by Aditya90456** [jahnvisahni31/DesignDeck#160]
![Aditya90456_CodeHive and 12 more pages - Personal 2 - Microsoft​ Edge Beta 10_18_2024 4_15_53 PM](https://github.com/user-attachments/assets/1c20bfd4-6cb4-4642-9edc-f45fabd0bffe)
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by powerstone666** [comment]
work on it...!

**Comment by Aditya90456** [comment]
> work on it...!

sure tomorrow working

**Comment by powerstone666** [comment]
make sure to use npm run build to resolve conflicts before submitting pr

**Comment by Aditya90456** [comment]
just notification get ?

**Comment by Aditya90456** [comment]
getting error when open @powerstone666

**Comment by powerstone666** [comment]
what error?can you describe it........!

**Comment by Aditya90456** [comment]
Unhandled Runtime Error
Error: NEXT_PUBLIC_LIVEBLOCKS_PUBLIC_KEY is not defined.

Source
liveblocks.config.ts (7:9) @ eval

   5 | // Ensure publicApiKey is properly retrieved from the environment
   6 | if (!process.env.NEXT_PUBLIC_LIVEBLOCKS_PUBLIC_KEY) {
>  7 |   throw new Error("NEXT_PUBLIC_LIVEBLOCKS_PUBLIC_KEY is not defined.");
     |         ^
   8 | }
   9 |
  10 | const client = createClient({

**Comment by Aditya90456** [comment]
i fix that by tomorrow @powerstone666
