### ISSUE TITLE
Enhancement: Pricing Page, add more content to the page 

### ISSUE THREAD

**Issue by shubhagarwal1** [jahnvisahni31/DesignDeck#163]
For now, the pricing page feels empty, i propose to add more content to the page 
hey @jahnvisahni31 please assign  me this task

**Comment by powerstone666** [comment]
k ill assign it

**Comment by shubhagarwal1** [comment]
Failed to build the project can you help,
<img width="1393" alt="Screenshot 2024-10-22 at 1 39 52 AM" src="https://github.com/user-attachments/assets/bddeed86-4717-4592-878d-e4324ebe7bd5">

**Comment by jahnvisahni31** [comment]
You should deploy with your own liveblocks api key in your .env.local file

**Comment by shubhagarwal1** [comment]
> You should deploy with your own liveblocks api key in your .env.local file

Hey @jahnvisahni31 i have created the .env.local file but still not abel to run the projec
<img width="1412" alt="Screenshot 2024-10-22 at 9 45 09 PM" src="https://github.com/user-attachments/assets/8191508e-15a8-4666-839a-23ccda2c6eb0">
