### ISSUE TITLE
gap between the navbar links

### ISSUE THREAD

**Issue by biswa2005** [jahnvisahni31/DesignDeck#167]
**Describe the bug**
the gap between the links of navbar is uneven 

**To Reproduce**
1. Go to website
2. see on the top right of the website
3. See error

**Expected behavior**
the gap should be even between the buttons to look good

**Screenshots**
![image](https://github.com/user-attachments/assets/32749933-93bf-4553-bb6a-712d29429c08)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Additional context**
please assign me this issue

**Comment by biswa2005** [comment]
please assign me this issue

**Comment by powerstone666** [comment]
issue is not that huge to be considered I'm closing this.......!
