### ISSUE TITLE
Good UI UX design for Sign up Button in NavBar

### ISSUE THREAD

**Issue by Surya-V-28** [jahnvisahni31/DesignDeck#168]
There is no proper hover effects for the NavBar SignUp Button and Dark mode component 

here is screenshot

![image](https://github.com/user-attachments/assets/99cf4bf1-0a4b-43ca-9c7d-7dc051772ebe)

and there is not transition effects on the dark mode component 

**Expected Behavior**
The signupButton should display a visible and smooth hover effect.
Dark mode transition should include a fade effect for a smoother user experience.

@powerstone666  @jahnvisahni31  please assign me this , i will make a soon after being assigned

**Comment by powerstone666** [comment]
along with that could you fix the uneven gap between navbar links?

**Comment by Surya-V-28** [comment]
@powerstone666  @jahnvisahni31  Sure i will take care

**Comment by jahnvisahni31** [comment]
go ahead @Surya-V-28

**Comment by Sourabh782** [comment]
> go ahead @Surya-V-28

hii @jahnvisahni31, this issues been open for about 3 week, so can i contribute to it?
