### ISSUE TITLE
 [UI/UX-Enhancement]-Redesign the Navbar for Improved Visual Appeal

### ISSUE THREAD

**Issue by AdityaP700** [jahnvisahni31/DesignDeck#170]
The current navbar needs a complete redesign to make it more visually appealing and enhance the overall user experience. The new design should focus on creating a modern, clean, and intuitive navigation system. Key elements to consider in the redesign include:

- Improved Layout: Rearrange elements for better usability and spacing, ensuring the navbar is responsive across devices (desktop, tablet, mobile).

- Visual Enhancements: Incorporate more vibrant colors, subtle gradients, or shadows to give the navbar a sleek and polished look. Consider adding hover effects to enhance interactivity.

- Typography: Use clearer, more legible fonts that fit well with the overall design of the website.
 E.g:
![Screenshot 2024-10-20 002631](https://github.com/user-attachments/assets/9c193820-4297-42be-a261-740af5c2fc2d)

**Comment by AdityaP700** [comment]
Hey @jahnvisahni31 ,can you look into this issue and let me assign me this issue under any Level between 2/3 of GSSOC-extd and HackOctoberFest. Thanks in Anticipation :)

**Comment by jahnvisahni31** [comment]
go ahead @AdityaP700

**Comment by AdityaP700** [comment]
@jahnvisahni31 thanks for assigning me this issue ,will be updating you soon
