### ISSUE TITLE
Creating Custom 404 page

### ISSUE THREAD

**Issue by dev129** [jahnvisahni31/DesignDeck#171]
Hi @jahnvisahni31 
**Is your feature request related to a problem? Please describe.**  
The current 404 error page on DesignDeck lacks a visually appealing design and doesn’t match the overall branding of the site. Additionally, the page's navigation bar doesn’t align with the rest of the website, creating a disjointed user experience. This inconsistency can leave visitors frustrated and cause them to abandon the site, especially when they encounter a broken link or incorrect URL.

**Describe the solution you'd like**  
I propose designing a custom 404 page that aligns with DesignDeck’s branding and offers a user-friendly experience. The page would feature a clean, visually engaging layout with the following elements:
- A playful or creative error message that reflects the brand's tone.
- A navigation bar consistent with the rest of the website.
- A prominent call-to-action button encouraging users to go back to the homepage or explore other parts of the site.
- A visually captivating design that reduces frustration and adds some personality to the error page.

**Describe alternatives you've considered**  
One alternative is to use a standard template for the 404 page, but this would miss the opportunity to engage users and keep them on the site. Another option is to include a search bar on the error page to help users find the content they were looking for. Both could be combined with the design, though the latter might clutter the simple aesthetic I have in mind.

**Additional context**  
A screenshot of the current 404 page and a comparison to DesignDeck's landing and other internal pages will help illustrate the inconsistency and the need for a cohesive design.

**Comment by jahnvisahni31** [comment]
go ahead @dev129

**Comment by dev129** [comment]
Hi @jahnvisahni31 
![image](https://github.com/user-attachments/assets/0d989e66-2422-491c-addd-5fbf633c205b)
just completed the wireframe design, I shall now start the design of the page.

**Comment by dev129** [comment]
Hi @jahnvisahni31 , this is the final design , please approve this so that I can launch a PR for it.

**Comment by dev129** [comment]
Hi @jahnvisahni31 , shall I launch the PR now ? I am waiting for your apptoval

**Comment by jahnvisahni31** [comment]
Yes sure
