### ISSUE TITLE
Creating FAQ section at the Landing Page

### ISSUE THREAD

**Issue by dev129** [jahnvisahni31/DesignDeck#172]
Hi @jahnvisahni31 
**Is your feature request related to a problem? Please describe.**  
The current FAQ section on DesignDeck is either missing or not organized effectively. This causes visitors to search through multiple pages for answers to common questions, leading to frustration and a poor user experience. A well-structured FAQ section is essential to provide quick, straightforward answers to common queries, ultimately improving user satisfaction.

**Describe the solution you'd like**  
I propose creating a dedicated FAQ section that is clear, easy to navigate, and provides concise answers to frequently asked questions. The section would:
- Be organized into categories for easier navigation.
- Feature collapsible questions for a cleaner look.
- Include a search functionality so users can quickly find relevant information.
- Be designed in a way that matches the overall aesthetics and branding of DesignDeck.

**Describe alternatives you've considered**  
An alternative solution would be to include a live chatbot to answer queries in real time. However, combining both the FAQ section and a chatbot would give users the best of both worlds—self-service answers for quick questions and live assistance when needed. Another option is to integrate an FAQ dropdown on each relevant page, but a dedicated FAQ page would provide a more comprehensive solution.

**Additional context**  
I can provide a wireframe for the FAQ section within 1 hour of approval, and I will deliver the final design within 24 hours of assignment. This design will ensure the section blends seamlessly with the overall look and feel of the website.

**Comment by jahnvisahni31** [comment]
go ahead @dev129

**Comment by dev129** [comment]
Hi @jahnvisahni31 
This is my wireframe for your project , and shall now start the designing phase.
![image](https://github.com/user-attachments/assets/6d2ebd9a-7250-4212-a146-d36f20f5a511)

**Comment by dev129** [comment]
I shall now start the designing phase.

**Comment by dev129** [comment]
Hi @jahnvisahni31 , shall I raise PR ?

**Comment by dev129** [comment]
Hi @jahnvisahni31 , shall I raise PR or not ?

**Comment by jahnvisahni31** [comment]
you should raise the pr 
no need to ask me 
i will review that also just mention which issue are you working on in the pr itself
