### ISSUE TITLE
[UI.UX Enchanment]  Pricing Card Page

### ISSUE THREAD

**Issue by Surya-V-28** [jahnvisahni31/DesignDeck#173]
the Current pricing card looking plane it can be made good

i have the  idea which might looks good 

![image](https://github.com/user-attachments/assets/ad098fa6-518c-4d50-9142-d2411037a26a)

Please assign me this issues i will work on it
![image](https://github.com/user-attachments/assets/c71be7da-9ce2-4079-90d1-e916afa07c07)

@jahnvisahni31  @powerstone666  under Gssoc and October fest

**Comment by jahnvisahni31** [comment]
go ahead @Surya-V-28

**Comment by Surya-V-28** [comment]
@jahnvisahni31  @powerstone666 
when im trying to run using  docker, im facing this issues 
 do you have any idea which helps me to resolve
 
![image](https://github.com/user-attachments/assets/3dc600b7-3975-4e55-a8ee-dcd072549306)

**Comment by Surya-V-28** [comment]
@powerstone666 @jahnvisahni31 any  solution for it ?
