### ISSUE TITLE
Search Bar in FAQ section

### ISSUE THREAD

**Issue by sandeepmaddheshiya** [jahnvisahni31/DesignDeck#177]
**Is your feature request related to a problem? Please describe.**
In FAQ section suppose i there are huge amount of lists, i want to find answer of some specific question then i've to manuaaly scroll and find that answer.

**Describe the solution you'd like**
The solution of that problem will be a searchbar to that section.

**Describe alternatives you've considered**
Alternatively I can add filters based on different categories of FAQ asked.

**Additional context**
![image](https://github.com/user-attachments/assets/8af8a849-c707-4d5b-b232-150df3ab8143)

**Comment by sandeepmaddheshiya** [comment]
Hey @jahnvisahni31  ,can you look into this issue and let me assign me this issue under any Level between 2/3 of GSSOC-extd and HackOctoberFest. Thanks in Anticipation :)

**Comment by powerstone666** [comment]
go ahead......

**Comment by sandeepmaddheshiya** [comment]
@powerstone666 I've created the PR, Please review it.
Thanks!

**Comment by jahnvisahni31** [comment]
hey just a remainder your pr has some issue please check that
