### ISSUE TITLE
Add Missing Meta Tags, Robots.txt, and Sitemap for Improved SEO

### ISSUE THREAD

**Issue by myselfshivams** [jahnvisahni31/DesignDeck#18]
The website currently lacks essential SEO elements such as meta tags, robots.txt, and a sitemap. These are critical for optimizing the site’s visibility on search engines and improving overall discoverability.

Proposed Solution:
- Meta Tags: Add relevant meta tags (title, description, keywords, Open Graph, Twitter cards, etc.) to improve SEO and social sharing.
- Robots.txt: Create a robots.txt file to guide web crawlers and define which pages should be indexed.
- Sitemap: Generate an XML sitemap to ensure proper indexing by search engines.

Benefits:
- Improved visibility on search engines.
- Better control over what pages should or should not be crawled.
- Enhanced user engagement via optimized metadata for sharing on social platforms.

Labels:
- gssoc
- hacktoberfest

@jahnvisahni31 Please assign this task to me(@myselfshivams).

**Comment by jahnvisahni31** [comment]
you can go ahead with the issue @myselfshivams

**Comment by jahnvisahni31** [comment]
its showing error till now i dont know why
