### ISSUE TITLE
UI fix: fix the header hover prop

### ISSUE THREAD

**Issue by AE-Hertz** [jahnvisahni31/DesignDeck#185]
header is having a issue with the signup on hover property.

![Screenshot 2024-10-22 113037](https://github.com/user-attachments/assets/b182d95e-bfd7-4425-af64-1317914fe75c)

assign me this under hacktoberfest and gssoc-ext

**Comment by Pheonixrog** [comment]
Please assign this task to me

**Comment by AE-Hertz** [comment]
@jahnvisahni31 hey , i really wanna know why you have marked this as completely?

**Comment by AE-Hertz** [comment]
@jahnvisahni31 i saw you assigned new issues and left old issues like this one as marked, this doesnot seem fair and how it should work.
