### ISSUE TITLE
[FEATURE] More font formatting styles and enable shortcuts 

### ISSUE THREAD

**Issue by mxyznk** [jahnvisahni31/DesignDeck#19]
**Feature description:**

1. Add options for more font formatting styles like Italic, ExtraBold, Strikethrough, Underline
2. Enable keyboard shortcuts, (eg. ctrl+B for bold)
3. Add more font options

**Proposed solution:**

- Google Fonts can be used, which will add a ton more font options
- Using JavaScript event listeners to capture keypresses. (extension of #2 )

**Comment by mxyznk** [comment]
I would like to contribute to this under gssoc-extd24 and hacktoberfest

**Comment by jahnvisahni31** [comment]
yes sure assigning you this

**Comment by Herostomo** [comment]
I would like to contribute to these issue

**Comment by jahnvisahni31** [comment]
its already assigned you may find or create issues that you think beneficial for our project or some changes you would like
