### ISSUE TITLE
Home Button Does Not Render Home Page After Clicking Terms of Use

### ISSUE THREAD

**Issue by Jyothishree2k5** [jahnvisahni31/DesignDeck#190]
**Describe the bug**
The Home button on the Terms of Use page does not redirect to the Home page, leaving the user stuck on the blank white page.
**To Reproduce**
1. Go to 'Footer section'
2. Click on 'Terms of use'
3. Scroll down to 'Home button'
4. See that is shows a blank white page

**Expected behavior**
Upon clicking the Home button, the user should be redirected to the Home page, which should render correctly and display the main content of the site.

**Screenshots**
After clicking the home button, a blank white screen appears as shown below
![Screenshot 2024-10-22 210549](https://github.com/user-attachments/assets/391c620a-3a45-49a0-a6b8-a46e4b395064)

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser: Chrome
- Version: 117.0.5938.88

**Smartphone (please complete the following information):**
- Device: Samsung Galaxy S21
- OS: Android 13
- Browser: Samsung Internet
- Version: 19.0.2.3

**Additional context**
Please assign this issue to me under gssoc-ext and hacktoberfest.

**Comment by jahnvisahni31** [comment]
okau go ahead @Jyothishree2k5
