### ISSUE TITLE
Adding scrollbar to the right sidebar

### ISSUE THREAD

**Issue by abhi9ab** [jahnvisahni31/DesignDeck#193]
**Is your feature request related to a problem? Please describe.**
The right sidebar content is not fully visible when the window size is set to normal dimensions. This causes frustration as users cannot access all the options and features available in the sidebar without resizing the window.

**Describe the solution you'd like**
Implement a scroll bar for the right sidebar to ensure that users can scroll through and access all the content, regardless of the window size.

**Describe alternatives you've considered**
An alternative solution could be to make the sidebar responsive and adjust its layout to fit the content dynamically. However, a scroll bar seems to be a more straightforward and user-friendly approach.

**Additional context**
This enhancement will improve the user experience by ensuring that all sidebar content is accessible at all times. Below is a screenshot of the current issue:

![Screenshot 2024-10-23 135031](https://github.com/user-attachments/assets/138a280e-4569-4152-b270-5d4ceed40392)

If the issue is approved, I would like to work on this.

**Comment by jahnvisahni31** [comment]
go ahead @abhi9ab
