### ISSUE TITLE
Deleting comment made by the user

### ISSUE THREAD

**Issue by abhi9ab** [jahnvisahni31/DesignDeck#194]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I make unnecessary comments or comments with mistakes, as I cannot delete them. This affects the clarity and quality of discussions within the design tool.

**Describe the solution you'd like**
I would like to have a feature that allows users to delete their own comments. This functionality should remove the comment and ideally replace it with a placeholder indicating that the comment was deleted by the user.

**Describe alternatives you've considered**
An alternative could be to edit comments instead of deleting them. However, this might not fully resolve the issue when a comment is entirely irrelevant or incorrect.

**Additional context**
This feature will enhance the user experience by allowing users to manage their comments more effectively, maintaining the quality and relevance of discussions.

If approved, i would like to get started with this issue.

**Comment by jahnvisahni31** [comment]
go ahead @abhi9ab
