### ISSUE TITLE
Add Keyboard Shortcuts

### ISSUE THREAD

**Issue by jahnvisahni31** [jahnvisahni31/DesignDeck#2]
**Issue**: Implement keyboard shortcuts for common actions such as saving, undo/redo, or selecting tools.

**Why**: Keyboard shortcuts can greatly improve the workflow for users.

**Task**:

1. Use JavaScript event listeners to capture keypresses.
2. Bind common actions to shortcut keys.

**Comment by Abhi0049k** [comment]
Hey @jahnvisahni31  I can work on this.

**Comment by jahnvisahni31** [comment]
yeah sure assigning you with this

**Comment by Abhi0049k** [comment]
Hello @jahnvisahni31, I am facing this issue while the running the project locally 
![image](https://github.com/user-attachments/assets/e34f52ea-2739-44f5-8f22-5a6822bd8cdd)

please guide me through this

**Comment by unknown91tech** [comment]
@jahnvisahni31 I can work on this issue too

**Comment by jahnvisahni31** [comment]
@Abhi0049k  for this you need to create a liveblocks api for your system and run this  and also just sign up and create api key and make according to that

**Comment by Abhi0049k** [comment]
Thank you, @jahnvisahni31! I was able to run the project locally.

**Comment by unknown91tech** [comment]
@jahnvisahni31 is this issue still open , as I have resolved the issue locally.

**Comment by Abhi0049k** [comment]
Hi @jahnvisahni31 

I hope this message finds you well. I wanted to let you know that I am currently facing some difficulties in implementing the keyboard shortcut feature for the project.

Unfortunately, I think it would be best to assign this issue to someone else who might be able to address it more effectively. I apologize for any inconvenience this may cause.

Thank you for your understanding!

Best regards,
Mangalam Kumar

**Comment by jahnvisahni31** [comment]
@unknown91tech  you can work on this if you want
