### ISSUE TITLE
On hover the value at sign in button is not visible

### ISSUE THREAD

**Issue by krishpathak** [jahnvisahni31/DesignDeck#202]
**Describe the bug**
On hover, the value at sign in button is not visible in the navbar

**Screenshots**
![image](https://github.com/user-attachments/assets/d26e01f3-d491-4146-9f65-47df80c1dd13)

@powerstone666 assign me a task, and i will fix it.

**Comment by jahnvisahni31** [comment]
go ahead @krishpathak
