### ISSUE TITLE
[Documentation] : Enhancement Of Contributing.md

### ISSUE THREAD

**Issue by milansamuel609** [jahnvisahni31/DesignDeck#203]
The contributing.md file is not in a structured manner. Also some sections are missing. I can enhance it in a well structured manner with proper details and some additional sections also that will make the contributors easier to contribute. Please can you assign me this task?

Wanted to do the following changes :-

1) Enhance the project structure
2) Add code of conduct section
3) Add star our repository section
4) Add need help with the basics section
5) Add first pull request steps section
6) Add additional method of contributing through GitHub desktop section
7) Add good coding practices section
8) Add the pull request rules section
9) Add the thank you section

**Comment by jahnvisahni31** [comment]
go ahead @milansamuel609
