### ISSUE TITLE
Navbar is not fixed.

### ISSUE THREAD

**Issue by aryadevesh** [jahnvisahni31/DesignDeck#21]
**Describe the bug**
The navbar is not fixed. It should be fixed for the whole website.

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/8eb2246f-a8f6-4e85-950a-e5986e81f2ad">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jahnvisahni31** [comment]
done assigned to you this issue

**Comment by aryadevesh** [comment]
Thanks Mam.

**Comment by jahnvisahni31** [comment]
done and succesfully closed
