### ISSUE TITLE
Auto label workflow automation🚀

### ISSUE THREAD

**Issue by amiya-cyber** [jahnvisahni31/DesignDeck#216]
Description: Create a GitHub Actions workflow that automatically labels new issues based on their content. This will help categorize and prioritize tasks for better project management.

note it will only add two labels hacktoberfest and gssoc ext

please @jahnvisahni31 assign this with level 3 label

**Comment by jahnvisahni31** [comment]
go ahead @amiya-cyber

**Comment by amiya-cyber** [comment]
hello @jahnvisahni31 can you assign me
