### ISSUE TITLE
redesign the ui of signup page 

### ISSUE THREAD

**Issue by REHAN-18** [jahnvisahni31/DesignDeck#218]
**Is your feature request related to a problem? Please describe.**
Currently, the sign-up page may look outdated or lack the cohesive style that aligns with the rest of the website. This mismatch can create a disjointed user experience, which is frustrating if the other pages have a modern, polished look.

**Describe the solution you'd like**
To give the sign-up page a fresh, cohesive aesthetic, consider these design elements:

**1-Minimalistic Layout**
*Use ample white space for a clean look.
*Center-align the form on the page, surrounded by subtle visual elements like soft gradients or shadows to make it stand out.
*Add rounded corners to input fields and buttons for a softer, modern look.
**2-Color Scheme**
*Match the form colors with the overall theme of the website.
*Use high-contrast, easy-to-read text on input fields and buttons.
*Apply a subtle background color (like a gradient or pastel tone) or a light blurred background to add visual depth.

**Describe alternatives you've considered**
Floating Form Design: Place the form in a semi-transparent floating container over a high-quality, blurred background image.

**Additional context**

**Comment by REHAN-18** [comment]
@jahnvisahni31 ma'am pls assign me !!!!

**Comment by jahnvisahni31** [comment]
could you go for login page as the sign up page has already been assigned to someone
if you could do login page then i will mark the labels

**Comment by REHAN-18** [comment]
> could you go for login page as the sign up page has already been assigned to someone if you could do login page then i will mark the labels

yes ok

**Comment by jahnvisahni31** [comment]
okay will give level 2
