### ISSUE TITLE
[UI Improvement] I want to redesign the Sign in and sign up page 

### ISSUE THREAD

**Issue by souvikpramanikgit** [jahnvisahni31/DesignDeck#220]
**Describe the bug**
[UI Improvement] I want to redesign the Sign in and sign up page 

**Here in the website the Sign in and sign up page, open in the different page, so i want to open the Sign in and sign up page in main page.**

**Screenshots**
![image](https://github.com/user-attachments/assets/07813b77-ef67-4d16-b144-768704019848)
![image](https://github.com/user-attachments/assets/0a443dd2-4ea4-448c-9582-5934704e33f0)

**Additional context**

**Comment by jahnvisahni31** [comment]
go ahead @souvikpramanikgit
