### ISSUE TITLE
Implement Strong Password Suggestion Feature

### ISSUE THREAD

**Issue by ananyag309** [jahnvisahni31/DesignDeck#227]
**Is your feature request related to a problem? Please describe.**  
Currently, users are able to create accounts with weak passwords, which could lead to security vulnerabilities and increase the risk of unauthorized access. This lack of guidance on creating strong passwords may result in users choosing simple or easily guessable passwords, compromising account security.

---

**Describe the solution you'd like**  
I would like to implement a strong password suggestion feature that automatically generates secure password options for users during registration and password reset. Additionally, a password strength indicator should be included to visually show users the strength of the passwords they choose. Guidance or tooltips could provide tips for creating strong passwords, such as recommending a mix of characters, numbers, and special symbols.

---

**Describe alternatives you've considered**  
1. Implementing a mandatory minimum password complexity policy without generating password suggestions.  
2. Using two-factor authentication (2FA) to add an extra layer of security, though this wouldn’t directly address weak passwords.  
3. Providing educational material on creating strong passwords but without an automated suggestion feature.

---

**Additional context**  
Adding these features would enhance the overall security of the platform and improve user experience by making it easier for users to understand password requirements. This feature would ensure users are more informed about password security, reducing the likelihood of account breaches.

**Comment by jahnvisahni31** [comment]
go ahead
@ananyag309
