### ISSUE TITLE
Email validation checker

### ISSUE THREAD

**Issue by ananyag309** [jahnvisahni31/DesignDeck#228]
**Describe the bug**
There is no email validation checker.

**Screenshots**
![image](https://github.com/user-attachments/assets/cebc77cf-5946-44ce-9374-7f64a8fb6b06)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser [e.g. chrome, safari]: chrome
 - Version [e.g. 22]: 22

**Comment by jahnvisahni31** [comment]
go ahead @ananyag309
