### ISSUE TITLE
sign up with Google Button

### ISSUE THREAD

**Issue by Aditya90456** [jahnvisahni31/DesignDeck#232]
adding button of sign up with
![design-deck vercel app_signup and 7 more pages - Personal 2 - Microsoft​ Edge Beta 11_1_2024 2_45_05 PM](https://github.com/user-attachments/assets/4b8927e7-6076-4066-a6d2-76b9be2b61a4)
Google

**Comment by jahnvisahni31** [comment]
Go ahead @Aditya90456

**Comment by Aditya90456** [comment]
i can't understand issue @jahnvisahni31 
![localhost_3000 and 3 more pages - Personal 2 - Microsoft​ Edge Beta 11_2_2024 1_02_24 PM](https://github.com/user-attachments/assets/826e420d-1aa7-414f-b407-7232d55957d3)

**Comment by Aditya90456** [comment]
Tomorrow evening and connect firebase?

**Comment by jahnvisahni31** [comment]
-Closed
