### ISSUE TITLE
Add stargaze timeline asset 

### ISSUE THREAD

**Issue by yashksaini-coder** [jahnvisahni31/DesignDeck#234]
**Is your feature request related to a problem? Please describe.**
My feat is simple to showcase the popularity & success of the project from the GSSoC-Ext & Hacktoberfest'24
run by adding a timeline stargaze animation effect.

**Describe the solution you'd like**
Adding a stargazers animated video asset of your project to be displayed with the contributors page or in another section for showcase effects

**Describe alternatives you've considered**

@jahnvisahni31 Can you assign me this issue as gssoc-ext contributor, and give level based on how good it is at the end result

**Comment by yashksaini-coder** [comment]
@jahnvisahni31 can you assign this issue to me

**Comment by jahnvisahni31** [comment]
Go ahead @yashksaini-coder
