### ISSUE TITLE
Dark mode/light mode toggle button not visible on safari browser, macOS

### ISSUE THREAD

**Issue by Peddinti-Sriram-Bharadwaj** [jahnvisahni31/DesignDeck#24]
**Describe the bug**
On Safari Browser, the dark mode icon/light mode is not visible. 

**To Reproduce**
1. Go to '.https://design-deck.vercel.app/#'
3. Scroll down to 'Home'

**Expected behavior**
Dark mode/light mode icons visible on all browsers. 

**Screenshots**
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/3479bbf3-19b4-4355-acc4-7d2be9914be8">
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/1dfec324-564e-436d-9630-39a963259045">

**Desktop (please complete the following information):**
 - OS: Macos [e.g. iOS]
 - Browser Safari[e.g. chrome, safari]
 - Version 18.1[e.g. 22]

**Smartphone (please complete the following information):**
 - Device: NA
 - OS: NA
 - Browser NA
 - Version NA

**Additional context**
furthermore, dark mode is not working as intended on multiple pages. I would like two work on them as well, by raising Issues.
please assign me to this issue, so that I can fix the browser specific UI issue.
request to please add the hactoberfest and gssoc-ext labels and a level-2 contribution labels as well.

**Comment by jahnvisahni31** [comment]
done assigned you this issue

**Comment by Peddinti-Sriram-Bharadwaj** [comment]
Thank you, I shall start working on this
