### ISSUE TITLE
Dark mode not working as intended on PC devices

### ISSUE THREAD

**Issue by Peddinti-Sriram-Bharadwaj** [jahnvisahni31/DesignDeck#25]
**Describe the bug**
Dark mode is not applied to the whole page on every browser, on both windows and macOS. Works fine on mobile devices however

**To Reproduce**
1. Go to '.https://design-deck.vercel.app'
2. Click on 'Darkmode/lightmode toggle button'
3. See error

**Expected behavior**
A proper dark mode applied to the whole page. 

**Screenshots**
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/15116bd0-b6d1-473e-961d-9b35e979e2f9">

**Desktop (please complete the following information):**
 - OS: Macos [e.g. iOS]
 - Browser Safari, Chrome, Edge, Brave, Firefox [e.g. chrome, safari]
 - Version 18.1, 129.0.6668.90 (Official Build) (arm64), Version 129.0.2792.79 (Official build) (arm64), 129.0.6668.89 (Official Build) (arm64)], 131.0 (aarch64) respectively[e.g. 22]

**Smartphone (please complete the following information):**
 - Device: NA
 - OS: NA
 - Browser NA
 - Version NA
 
**Additional context**
please assign me to this issue, so that I can fix the browser agnostic UI issue.
request to please add the hactoberfest and gssoc-ext labels and a level contribution labels as well.

**Comment by jahnvisahni31** [comment]
done assigned you this issue
