### ISSUE TITLE
Bug: Reviews in Dark mode 

### ISSUE THREAD

**Issue by AkashJana18** [jahnvisahni31/DesignDeck#250]
**Describe the bug**

**To Reproduce**
1. Go to https://design-deck.vercel.app/
2. Turn on dark mode
3. Scroll down to review

**Expected behavior**
Should Clear and visible

**Screenshots**
Unclear and not visible
![image](https://github.com/user-attachments/assets/a074910d-e2e8-4fd9-9432-d68c5ec4865a)

**Additional context**
Please assign me the issue and add relevant gssoc tags.

**Comment by jahnvisahni31** [comment]
go ahead @AkashJana18
