### ISSUE TITLE
Navbar is not responsive in mobile version

### ISSUE THREAD

**Issue by Hemraj-7** [jahnvisahni31/DesignDeck#251]
**Describe the bug**
In the mobile version nav is not looking good.

**Expected behavior**
I want to add hamburger menu at right side of the navbar and left side add the logo of our website. and make it responsive and user friendly.

**Screenshots**
![Screenshot 2024-11-07 143310](https://github.com/user-attachments/assets/295d0ef7-44b0-4ddf-adbf-17386f64c576)

I want to work on this issue please assign me 
Thank you!

**Comment by jahnvisahni31** [comment]
go ahead @Hemraj-7

**Comment by Hemraj-7** [comment]
Hii @jahnvisahni31 can you help me , I'm getting this error every time 

![Screenshot 2024-11-07 155614](https://github.com/user-attachments/assets/eacdba91-5ea8-4b2b-b7ff-2fdbb4389f61)

**Comment by Hemraj-7** [comment]
![Screenshot 2024-11-07 155842](https://github.com/user-attachments/assets/87dc3577-afab-47fd-b8ec-4f16ce87125d)
