### ISSUE TITLE
 Body Design: Enhance Visual Appeal and Space Utilization

### ISSUE THREAD

**Issue by kekubhai** [jahnvisahni31/DesignDeck#26]
**Solution:**

I propose enhancing the guitar body design by:

* Optimizing the "Never" element to reduce its size or font and free up space.
* Filling the black areas with visually appealing elements, such as patterns, textures, or additional information.
* Implementing 3D features using Three.js or Spline.js to create a more dynamic and visually engaging experience.

**Alternatives:**

* **Simpler design:** While a simpler design might be less visually complex, it may not address the issues of space utilization and visual appeal.
* **Static elements:** Using static elements instead of 3D features could be less visually dynamic, and it may not provide the same level of engagement.

**Additional context:**

![image](https://github.com/user-attachments/assets/26728ba8-b0fc-404b-b17e-16a950f0fe34)

[Insert any relevant screenshots or additional information about the guitar body design here.]

![image](https://github.com/user-attachments/assets/505fd704-40f8-4d9d-9779-5b7f73db192c)

By implementing these enhancements, we can create a more visually engaging and aesthetically pleasing guitar body design that effectively utilizes the available space and provides a better overall user experience.

Please assign me this issue, I would like to work on it

**Comment by jahnvisahni31** [comment]
done assigned you this issue

**Comment by kekubhai** [comment]
The navbar is all set here like this : 
![image](https://github.com/user-attachments/assets/9c23f06e-ac00-4c05-be25-ac682e559171)
. 
Also Can i install npm packages to add 3d components from spline and three.js ? 
Thank you

**Comment by kekubhai** [comment]
Thanks for this also for today I could have only done this . Please check it out . https://github.com/user-attachments/assets/593d02fa-a424-4285-8dc0-48a1040cf462



Thank you

**Comment by jahnvisahni31** [comment]
okay no problem you can take your time

**Comment by kekubhai** [comment]
sorry for being so late, I raised the PR , there are some merge conflicts which I could not resolve Please look into that. sorry for some of the enhancement I could not implement. Thank You
