### ISSUE TITLE
Implementing OTP based forgot password frontend + backend

### ISSUE THREAD

**Issue by Sourabh782** [jahnvisahni31/DesignDeck#263]
**Is your feature request related to a problem? Please describe.**

As we are providing users an option to login or signup, what happends if user forgot their password. Theres no way for users to get their account back if they forget their password

**Describe the solution you'd like**

I would like to implement forgot password functionality, so users can reclaim their account if they forgot their password.

my idea: 
1. user enters their mail id
2. an otp is sent to user's mail id
3. user enters the otp
4. backend verifies the otp
5. user resets his password

This will add more security and it will be an additional feature, to help users reclaim their account

**Additional context**

![image](https://github.com/user-attachments/assets/aab37146-71b6-4cf2-ad27-a8ece974a138)

**Comment by jahnvisahni31** [comment]
go ahead @Sourabh782
