### ISSUE TITLE
Testimonials not visible in dark mode

### ISSUE THREAD

**Issue by Sourabh782** [jahnvisahni31/DesignDeck#264]
**Describe the bug**

**To Reproduce**
1. Go to home page, scroll down for testimonials

**Expected behavior**
There should be proper contract with background to show important information

**Screenshots**

![image](https://github.com/user-attachments/assets/e4fa14ba-7901-4bd6-915a-0c5f7e103f01)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] chrome

**Additional context**

**Comment by jahnvisahni31** [comment]
go ahead @Sourabh782
