### ISSUE TITLE
Add GitHub Workflow for Auto-Closing Similar Issue Requests

### ISSUE THREAD

**Issue by souvikpramanikgit** [jahnvisahni31/DesignDeck#269]
**Is your feature request related to a problem? Please describe.**

Add GitHub Workflow for Auto-Closing Similar Issue Requests

## Description

This duplicate detection workflow significantly streamlines project management by automatically reducing redundant issues, helping maintainers focus on unique, unresolved problems. It saves time by automating the identification and closure of similar issues, preventing contributors from repeatedly addressing the same questions or bugs. With a clear link to the original issue, users can easily follow updates, improving transparency and reducing confusion. The feature enhances productivity by keeping the issue list organized, ensuring that attention goes to high-priority or novel issues. Overall, it fosters a more efficient, user-friendly environment, promoting collaboration and faster resolution of project needs.

**Additional context**

**Comment by jahnvisahni31** [comment]
go ahead @souvikpramanikgit

**Comment by souvikpramanikgit** [comment]
@jahnvisahni31
