### ISSUE TITLE
Feat:Enhance Navbar Hover Animations, Alignment and Logo Size

### ISSUE THREAD

**Issue by rohitmore07** [jahnvisahni31/DesignDeck#276]
### Description :
The current navbar could benefit from a few UI enhancements to improve overall aesthetics and user experience. Here’s what I propose :

**1) Hover Animations :** Add smooth and subtle hover animations to navbar items to make interactions more engaging.
**2) Alignment:** Improve the alignment of the navbar items to ensure they are evenly spaced and visually balanced.
**3) Logo Size :** Adjust the logo size to maintain a consistent look, ensuring it complements the rest of the navbar elements without being too large or too small.

**Benefits :**

- Enhances the visual appeal and interactivity of the navbar.
- Provides a more polished and professional look, ensuring a better user experience.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/5625ec9c-2031-4053-bcb4-3ddd2876f963)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by jahnvisahni31** [comment]
go ahead @rohitmore07

**Comment by rohitmore07** [comment]
@jahnvisahni31 When attempting to run the development server with npm run dev, the following error occurs:
'next' is not recognized as an internal or external command, operable program or batch file.

**Steps Tried**
Ran npm install to install dependencies, but the issue persists.
Manually installed next by running npm install next, but it didn’t resolve the problem.
Verified Node.js and npm installation; both are up-to-date and recognized in the system PATH.
Attempted using npx next dev as a workaround, but a permanent fix is needed.

**Expected Behavior**
The command npm run dev should start the Next.js development server without issues.

**Request**
Any guidance on resolving this issue would be appreciated. Could this be related to a missing dependency or PATH configuration? Please advise on further troubleshooting steps.
