### ISSUE TITLE
Adding a login and signup page

### ISSUE THREAD

**Issue by Sourabh782** [jahnvisahni31/DesignDeck#28]
**Is your feature request related to a problem? Please describe.**
As the app contains option for login and signup, but currently it dont have those pages, so i want to implement those pages

**Describe the solution you'd like**
I wanted to design and add login and signup page

**Additional context**
![Screenshot 2024-10-04 201129](https://github.com/user-attachments/assets/51ecd38c-1b41-4cff-bffd-fd2e20379546)

**Comment by unknown91tech** [comment]
@jahnvisahni31 I can start working on this issue

**Comment by Sourabh782** [comment]
@unknown91tech  its against rule, according to the rules the person creating issue will be assigned that issue

**Comment by jahnvisahni31** [comment]
yes you can go ahead with it @Sourabh782  i am assigning this to you

**Comment by Sourabh782** [comment]
Thanks @jahnvisahni31 on it

**Comment by iamsohelx** [comment]
hey @jahnvisahni31 if @Sourabh782 is not working on this issue, could you please assign me this issue

**Comment by Sourabh782** [comment]
@iamsohelx I am working on it

**Comment by Sourabh782** [comment]
Hii @jahnvisahni31, i have completed frontend, can you tell me which database to use

**Comment by Sourabh782** [comment]
@jahnvisahni31 can you specify the database?

**Comment by jahnvisahni31** [comment]
use  prisma

 yes 
 sorry for late repy

**Comment by Sourabh782** [comment]
> use prisma
> 
> yes sorry for late repy

Ohkk, I'll implement backend👍👍
