### ISSUE TITLE
Enhance Mobile Responsiveness

### ISSUE THREAD

**Issue by jahnvisahni31** [jahnvisahni31/DesignDeck#3]
**Issue**: Make sure that all pages and components are mobile-friendly using Tailwind CSS.

**Why**: Mobile responsiveness is essential for a good user experience on all devices.

**Task:**
1. Test the current state of mobile responsiveness.
2. Add or modify CSS classes to ensure the layout adjusts properly on smaller screens.

**Comment by Peddinti-Sriram-Bharadwaj** [comment]
Dear project admins, I would like to work on this issue. 
if you could assign me to this issue, I shall work on it on mobile screens of various form factors.
I can add the appropriate classes to fix the issues (if any), and make the UI more responsive.

**Comment by jahnvisahni31** [comment]
yes sure i will assign you this

**Comment by Peddinti-Sriram-Bharadwaj** [comment]
Thank you, I shall start working on this

**Comment by n-keerthi-gayathri** [comment]
@jahnvisahni31 please assign me this issue

**Comment by Sourabh782** [comment]
@jahnvisahni31 i see this issue has no assignee, so can i work on it?

**Comment by n-keerthi-gayathri** [comment]
@jahnvisahni31 please assign me this issue

**Comment by jahnvisahni31** [comment]
go ahead with @n-keerthi-gayathri
