### ISSUE TITLE
Changing the section as requested

### ISSUE THREAD

**Issue by unknown91tech** [jahnvisahni31/DesignDeck#30]
![image](https://github.com/user-attachments/assets/0167ce10-15c7-4d8a-bb3f-c96311c059a5)

Changing this section and adding  the features instead. @jahnvisahni31 can you assign this issue to me

**Comment by unknown91tech** [comment]
@jahnvisahni31 I have added the pr

**Comment by jahnvisahni31** [comment]
#32 closed and completed
