### ISSUE TITLE
Redesigning of header and footer to uplift ui/ux  and user accessibility  fix

### ISSUE THREAD

**Issue by abhishekpanthee** [jahnvisahni31/DesignDeck#31]
- Redesigning of header and footer to uplift ui/ux  
- i did see an issue of 404 page i could do that also  as it is not submitted 
- and a bug as in mobile view without having to sign in we get other options when we are signed in 
![Screenshot from 2024-10-05 00-50-23](https://github.com/user-attachments/assets/b3346446-fb7a-4813-974c-0163a1aa2f30)

**Comment by jahnvisahni31** [comment]
yes sure make sure to star the repo first and fork first

**Comment by jahnvisahni31** [comment]
#36 done and completed

**Comment by jahnvisahni31** [comment]
done
