### ISSUE TITLE
[ BUG ] : The questions in the FAQ page is not visible in the light mode.

### ISSUE THREAD

**Issue by 1-SubhamSingh** [jahnvisahni31/DesignDeck#33]
**Describe the bug**
The questions  in the FAQ page is not visible in the light mode.

**Expected behavior**
The questions  in the FAQ page should be visible in the light mode.

**Screenshots**
In the  light mode
![image](https://github.com/user-attachments/assets/535168ea-90c7-4b75-97a4-2ad45244dd0c)

In the dark mode
![image](https://github.com/user-attachments/assets/ce8bb8f0-3ca1-42d6-bd7e-913193914c6b)

I'll fix this issue , @jahnvisahni31  can you please assign me this task under the labels -  GSSoC extnd  along with its level and Hacktoberfest2024.
Thanks in advance :)

**Comment by jahnvisahni31** [comment]
you can go ahead with this issue @1-SubhamSingh

**Comment by Kuldeepsinghrajpoot** [comment]
![image](https://github.com/user-attachments/assets/b7eb0f5a-46ee-48ef-a7c3-5fe010472c58)
Dark mode and light mode are not showing here. Instead, a blue button is visible, but the type of buttons inserted into the navigation bar is not displaying correctly

**Comment by Kuldeepsinghrajpoot** [comment]
![image](https://github.com/user-attachments/assets/96d56952-049f-408b-b6fd-1c7185d71b38)

It is not working in the responsive version. The elements and navbar items that were inserted into the navbar are not hidden, such as the settings icon. These elements remain visible in the responsive version
