### ISSUE TITLE
Editing tools hover changes - problem

### ISSUE THREAD

**Issue by YasirKhan231** [jahnvisahni31/DesignDeck#37]
While we hover on the editing tools on the dark mode then tools color is not showing . Because of the black color not changing while we change to dark mode 

![image](https://github.com/user-attachments/assets/11974507-519e-456a-bd94-9fd40921ec0b)

 also this 

![image](https://github.com/user-attachments/assets/35ab4ca1-c29c-4bac-b226-4937520c856b)

**Comment by jahnvisahni31** [comment]
Yes sure you can go ahead @YasirKhan231

**Comment by YasirKhan231** [comment]
ok i work on this
