### ISSUE TITLE
Addition of All Contributors Photos in Readme | Readme Updation 

### ISSUE THREAD

**Issue by shubhagarwal1** [jahnvisahni31/DesignDeck#39]
We can add a file in workflows to add the contributors automatically to readme which basically enhaces the repo visibility
Hey @jahnvisahni31 please assign this task to me with level tag

**Comment by jahnvisahni31** [comment]
you can go with this @shubhagarwal1

**Comment by jahnvisahni31** [comment]
THERE ARE CONFLICTING FILES PLEASE CHECK
