### ISSUE TITLE
Implement Dark Mode

### ISSUE THREAD

**Issue by jahnvisahni31** [jahnvisahni31/DesignDeck#4]
**Issue**: Add a toggle for dark mode to enhance user experience.

**Why**: Dark mode is increasingly popular and can reduce eye strain for users in low-light conditions.

**Task:**

1. Create a toggle switch for dark/light mode.
2. Update Tailwind CSS classes to reflect changes based on the selected mode.

**Comment by unknown91tech** [comment]
@jahnvisahni31 can I use NextUi library do do this?

**Comment by jahnvisahni31** [comment]
Yes, you can definitely use the NextUI library to implement a dark mode toggle for your project! @unknown91tech 
i am assigning this to you please check the coding contribution guidelines first

**Comment by unknown91tech** [comment]
have created a pull request , can you check and confirm that every thing is working?

**Comment by unknown91tech** [comment]
I have created a pull request but now realized that the last merged code isn't there in the pr that I made so what should I do?

**Comment by jahnvisahni31** [comment]
you could add that file or i delete that pr and you can raise the pr again?

**Comment by unknown91tech** [comment]
I will add all the file with my pr

**Comment by unknown91tech** [comment]
@jahnvisahni31 can you delete that pr so that I can add a new one ??

**Comment by jahnvisahni31** [comment]
done that close that pr generate a new one

**Comment by unknown91tech** [comment]
I have made a pr

**Comment by jahnvisahni31** [comment]
yes i have told the changes in the pr itself make sure to check that @unknown91tech  and do the necessary
