### ISSUE TITLE
Change the appearance of the Dark/Light Mode Toggle

### ISSUE THREAD

**Issue by Priyesh017** [jahnvisahni31/DesignDeck#40]
### **Change the appearance of the Dark/Light Mode Toggle Button**

**Problem:**

- The Present Dark/Light Mode Toggle Button doesn't appear visually appealing.

**Solution:**

- I would like to use Dark/Light icon from react-icons to make it visually appealing.

**Alternate Solution:**

- If you have a better looking icon in your mind, please mention the name and resource.

Hey @jahnvisahni31, please assign me this issue under the label "GSSoC-Extd'24" and "Hacktoberfest'24" to make contribution count.

I have read the guidelines and starred the repository.
I'm willing to contribute to this repository if you have any other suggestion for me please mention it as this is my first time open source contribution.

**Reference to the problem:**

![Screenshot 2024-10-06 164411](https://github.com/user-attachments/assets/f9703434-cc57-4db1-9f2f-db0e099043fd)

**Comment by jahnvisahni31** [comment]
go ahead with this @Priyesh017

**Comment by Priyesh017** [comment]
> go ahead with this @Priyesh017

Hey @jahnvisahni31, is there any time limit within October to solve this issue?

**Comment by jahnvisahni31** [comment]
YES 
IT WILL BE COUNTED TILL OCT 31

**Comment by Priyesh017** [comment]
> YES 
> IT WILL BE COUNTED TILL OCT 31

Got it
