### ISSUE TITLE
Login / signup backend

### ISSUE THREAD

**Issue by Sourabh782** [jahnvisahni31/DesignDeck#41]
**Describe the solution you'd like**
As the app has login signup option, i wanted to add backend for login and signup functionality/

![image](https://github.com/user-attachments/assets/7ca5b1f4-87b6-425b-a7d1-003eb256f830)

**Comment by jahnvisahni31** [comment]
why are you making this issue once again i have assigned you this already

**Comment by Sourabh782** [comment]
@jahnvisahni31 i was asking for backend functionality. 
previously i am working on frontend part: 
![image](https://github.com/user-attachments/assets/e0a68463-9fc9-4602-85fd-483455dfb7f1)

**Comment by jahnvisahni31** [comment]
make it in one part

**Comment by Sourabh782** [comment]
@jahnvisahni31 but u mentioned it as level1 task? for both frontend and backend can u reconsider elevating it?
