### ISSUE TITLE
Dark/light mode toggle button not showing

### ISSUE THREAD

**Issue by Sourabh782** [jahnvisahni31/DesignDeck#42]
**Describe the bug**
The dark/light mode is not showing

**To Reproduce**
open the app

**Expected behavior**
there should be a proper element showing light/dark mode

**Screenshots**
![image](https://github.com/user-attachments/assets/9d200434-5452-42f1-9076-dc7a2efe59e6)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome

**Comment by jahnvisahni31** [comment]
You can work on this

**Comment by Sourabh782** [comment]
@jahnvisahni31 can you close previous one, that one not showing in my issues section
