### ISSUE TITLE
Improvement Of navbar issue✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [jahnvisahni31/DesignDeck#45]
**Is your feature request related to a problem? Please describe.**

https://github.com/user-attachments/assets/d765c781-7eb8-4690-bd99-731ffc78cf64

**Describe the solution you'd like**
there is conflict on the navbar over the content and the  i can make the dark mode toggle as well , please assign me this task.

**Comment by jahnvisahni31** [comment]
it is working fine
