### ISSUE TITLE
Login/signup page creation✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [jahnvisahni31/DesignDeck#46]
**Is your feature request related to a problem? Please describe.**
<img width="156" alt="Screenshot 2024-10-06 at 8 58 12 PM" src="https://github.com/user-attachments/assets/84c5ef0b-5cb4-4439-a194-5829535f4e38">

**Describe the solution you'd like**
these singup/login pages arent created/working , if u assign me this task ill create them . @jahnvisahni31 please assign me this task.

**Comment by jahnvisahni31** [comment]
someone is already working on this issue
