### ISSUE TITLE
 Implement Layer Management Functionality

### ISSUE THREAD

**Issue by jahnvisahni31** [jahnvisahni31/DesignDeck#5]
**Issue**: Enhance the layers panel to allow users to add, delete, and reorder layers.

**Why**: Layer management is crucial for organizing design elements effectively.

**Task:**

1. Create UI elements for adding, removing, and reordering layers.
2. Implement functionality to update the canvas display based on layer visibility and order.

**Comment by harish08102004** [comment]
Hey @jahnvisahni31 I can work on this.

**Comment by jahnvisahni31** [comment]
You can go ahead

**Comment by jahnvisahni31** [comment]
also make sure to star the repo first

**Comment by harish08102004** [comment]
![image](https://github.com/user-attachments/assets/ae2bc591-46ca-49f8-bf90-4d84482612f7)
I'm getting this error.

**Comment by jahnvisahni31** [comment]
Delete node_modules and package-lock.json, update next.config.mjs by removing appDir, uninstall @next/font, update imports to next/font, ensure Tailwind's content array includes the correct paths, and reinstall dependencies with npm install. you could see this if this works

**Comment by harish08102004** [comment]
Ok I will check it
