### ISSUE TITLE
Enhance Faq Page UI 🔴

### ISSUE THREAD

**Issue by Kishore-kumar-07** [jahnvisahni31/DesignDeck#50]
hi @jahnvisahni31 , 

Your site ui good but the faq page is not in sync with the other pages

I would like to enhance The ui of the **faq** page 

kindly assign me this issue under gssoc extd and add labels **gssoc extd** and **hactoberfest**

**Comment by jahnvisahni31** [comment]
go ahead with this @Kishore-kumar-07
