### ISSUE TITLE
Issue in Faq Page

### ISSUE THREAD

**Issue by PankajKumardev** [jahnvisahni31/DesignDeck#57]
In Light mode the Frequently Asked Questions (FAQ) page have issue that the font is in white color and background also in white color .

![image](https://github.com/user-attachments/assets/1b1bd23f-a5de-49b3-88f5-bbcedc3ac9cd)

**Comment by jahnvisahni31** [comment]
it is already there in issues someone is working on this

**Comment by PankajKumardev** [comment]
Ok
