### ISSUE TITLE
Dark Mode Button Issue

### ISSUE THREAD

**Issue by Jazz-45** [jahnvisahni31/DesignDeck#59]
**Describe the bug**
Dark Mode button does mot have any text that tells the functionality of this button.

**To Reproduce**
1. Go to 'website'
2. Click on 'bule button on top right'

**Expected behavior**
There should be an clear text or at least an icon that indicates that this is the toggle button for and light mode.

**Screenshots**

![Screenshot 2024-10-08 093558](https://github.com/user-attachments/assets/f294972a-aaca-4944-a66b-c66adf1b6b26)
![Screenshot 2024-10-08 093614](https://github.com/user-attachments/assets/4db51873-6a23-4283-ac40-df5caa8f2728)

**Desktop (please complete the following information):**
 - Windows
 - chrome
 - 11

**Additional Efforts to improve**
Not only I will add text but also add a good icon that will overall improve the look and user experience of the website.
I will also change the neon shades of colors and pick the colors that matches the color schema of the website.

**Comment by jahnvisahni31** [comment]
someone is already working on this
