### ISSUE TITLE
Implement Color Picker for Text and Shapes

### ISSUE THREAD

**Issue by jahnvisahni31** [jahnvisahni31/DesignDeck#6]
**Issue:** Create an interactive color picker for changing the text and shape colors.

**Why**: Users should have the ability to customize colors easily.

**Task**:

1. Implement a color picker UI (could use a library).
2. Ensure that selecting a color updates the color of selected elements on the canvas.

**Comment by priyanshuverma-dev** [comment]
Hi @jahnvisahni31,
I would like to work on this issue.
Let you do what your mind things 💡

**Comment by jahnvisahni31** [comment]
yes sure will assign you this

**Comment by Herostomo** [comment]
hi @jahnvisahni31 
I also want to work on thus issue
