### ISSUE TITLE
Add Contact us page

### ISSUE THREAD

**Issue by Saaarthak0102** [jahnvisahni31/DesignDeck#60]
**Is your feature request related to a problem? Please describe.**
The website currently lacks a "Contact Us" page, which is important for user communication and support. A dedicated "Contact Us" page should be added to allow users to reach out for inquiries or support.

**Describe the solution you'd like**
A functional "Contact Us" page with:

A user-friendly form including fields for Name, Email, Subject, and Message.
Backend support for receiving and processing submissions.
A confirmation message or email notification upon successful submission.

**Describe alternatives you've considered**
An alternative could be integrating a contact form directly into the footer of the website instead of a standalone page, or using a pop-up form triggered by a "Contact" button.

**Additional context**
The page should align with the overall design and theme of the website. A reference for design inspiration could be the current design deck page at https://design-deck.vercel.app/.

**Comment by Dhruv-pahuja** [comment]
@jahnvisahni31 As i can see there is no update on this feature , so can you please assign it to me , so that I can complete this fast 
'

**Comment by jahnvisahni31** [comment]
already someone has done that

**Comment by Saaarthak0102** [comment]
i was working on it :)
