### ISSUE TITLE
i found issue in Wokspace  

### ISSUE THREAD

**Issue by goli17** [jahnvisahni31/DesignDeck#61]
The UI of navbar/header in workspace can be further polished, and the dropdown needs enhancement.
like active  icon color spacing  

<img width="1680" alt="Screenshot 2024-10-08 at 1 45 52 PM" src="https://github.com/user-attachments/assets/1303cf05-c904-4ede-ae01-b873a64453eb">

here  right click menu needs improvements

<img width="1680" alt="Screenshot 2024-10-08 at 1 45 23 PM" src="https://github.com/user-attachments/assets/efab5129-cb32-45c5-969e-8efb014338b4">

**Comment by jahnvisahni31** [comment]
okay go ahead with this @goli17

**Comment by goli17** [comment]
@jahnvisahni31  ok Thanks
