### ISSUE TITLE
Navbar 

### ISSUE THREAD

**Issue by vverma022** [jahnvisahni31/DesignDeck#62]
**Describe the bug**
The navbar has options to go to the dashboard etc but it does not work. Due to user not being authenticated so remove this and make the navbar responsive so that it shows only if user is logged-in etc. Additionally improve the navbar and its design. 

**Additional context**
<img width="1440" alt="Screenshot 2024-10-08 at 2 42 52 PM" src="https://github.com/user-attachments/assets/c55c320e-e260-4272-aba2-06f5ea4a2820">

**Comment by vverma022** [comment]
Can I be assigned this under GSSoC Ext '24 and Hacktoberfest

**Comment by PrayanshParmar** [comment]
@vverma022 please wait I have alreday added auth in this project, but Admin is not merging my code. Then you can fix the UI of navbar

**Comment by jahnvisahni31** [comment]
already someone is working
