### ISSUE TITLE
Adding Subscription model details in pricing page in the footer

### ISSUE THREAD

**Issue by master-ginger** [jahnvisahni31/DesignDeck#64]
The pricing page is not developed yet and I would like to create one for DesignDeck
![image](https://github.com/user-attachments/assets/059493b9-5e46-4bcf-bbf2-a17a664d4ad3)
![image](https://github.com/user-attachments/assets/ccf0e903-1954-4e93-8a18-99c159629009)

I would like to add subscription plans to the pricing page where each package will have its unique features and additional tools. For example, Basic user plan, Silver plan, gold plan and diamond plan.

**Comment by jahnvisahni31** [comment]
sure go ahead with this @master-ginger
