### ISSUE TITLE
Navigation not responding

### ISSUE THREAD

**Issue by Kuldeepsinghrajpoot** [jahnvisahni31/DesignDeck#66]
Here's an updated version of your request with that addition:

"The navigation and navigation pages are not working correctly, and the responsive version is not working. Could you assign me to resolve these issues? Additionally, I need to add a registration page and implement login using NextAuth. NextAuth has no daily or monthly request limits for accepting incoming user data compared to Clerk."

This now includes both issues with the navigation and the request to add the registration and login features.

**Comment by jahnvisahni31** [comment]
already someone is working
