### ISSUE TITLE
Type to Text and Shapes not working

### ISSUE THREAD

**Issue by haseebzaki-07** [jahnvisahni31/DesignDeck#67]
**Describe the bug**
Type to Text on the workspace  page is not working along with the shapes creation

**To Reproduce**
1. Go to workspace
2. Click on Type to Text
3. See error

**Expected behavior**
Ideally the text we typ should reflect on the canvas

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jahnvisahni31** [comment]
go ahead @haseebzaki-07
