### ISSUE TITLE
Add Automated Greeting Workflow

### ISSUE THREAD

**Issue by shubhagarwal1** [jahnvisahni31/DesignDeck#7]
**Describe the solution you'd like**
I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository. The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.
Hey @jahnvisahni31  please assign me this task under labels

**Comment by jahnvisahni31** [comment]
"make sure to fork and star the repo first before contributing" add this in your greeting message as well

**Comment by jahnvisahni31** [comment]
also make something meaningful changes to the repo

**Comment by jahnvisahni31** [comment]
closed with pull

**Comment by shubhagarwal1** [comment]
> closed with pull

please assign the labels on PR as well

**Comment by jahnvisahni31** [comment]
#8 closed and completed
