### ISSUE TITLE
Bug Report: Icons Not Visible in Dark Mode

### ISSUE THREAD

**Issue by Rizvi-Faiz** [jahnvisahni31/DesignDeck#73]
### Bug Report: Icons Not Visible in Dark Mode

**Description:**
Some icons are not visible when using dark mode. This issue makes it difficult to navigate or understand the functionality of the affected icons.

**Steps to Reproduce:**
1. Switch to dark mode on the application.
2. Navigate to the section where icons are used (specify the affected section(s) if possible).
3. Observe that certain icons are not visible or are difficult to see.

**Expected Behavior:**
Icons should be clearly visible and distinguishable in both light and dark mode.

**Actual Behavior:**
Icons are either not visible or are too faint to be seen in dark mode.

**Screenshots:**
![image](https://github.com/user-attachments/assets/5c95dbc9-a4c1-403e-a598-fec9223ed4d2)
![image](https://github.com/user-attachments/assets/8318e745-aa9b-41a9-89f1-6bc8ab1e58db)

**Environment:**
- **Browser/Device:** _e.g., Chrome, Firefox, Safari, etc._
- **Operating System:** _e.g., Windows, macOS, Linux, etc._
- **Dark Mode Enabled:** Yes

**Possible Solution:**
Review the color contrast of the icons in dark mode and adjust them to ensure they meet accessibility standards. Consider using light-colored icons or adding background contrast for better visibility.

**Comment by Rizvi-Faiz** [comment]
@jahnvisahni31 can you assign this issue to me

**Comment by jahnvisahni31** [comment]
YEAH GO AHEAD @Rizvi-Faiz
