### ISSUE TITLE
Ad support page

### ISSUE THREAD

**Issue by Rizvi-Faiz** [jahnvisahni31/DesignDeck#74]
### Feature Request: Add Support Us Page

**Description:**
We need to add a "Support Us" page to the website or project. This page will allow users to understand how they can contribute to the project, either financially or through other means (e.g., starring the repo, contributing to the code, etc.).

**Proposed Solution:**
Create a new page with the following sections:
- Why Your Support Matters
- Ways to Support Us:
  - Star the Project on GitHub
  - Contribute to the Code
  - Share the Project with Others
  - Donate or Sponsor the Project (if applicable)

**Acceptance Criteria:**
- [ ] Page layout and content structure finalized.
- [ ] Sections on how to support us, including links to GitHub, contribution guidelines, and donation options.
- [ ] Styling consistent with the rest of the website (or project).
- [ ] Page accessible through the main navigation or footer.

**Additional Context:**
Include links to the GitHub repo, contribution guide, and any donation/sponsorship platforms.

**Comment by Rizvi-Faiz** [comment]
@jahnvisahni31 please assign this to me

**Comment by jahnvisahni31** [comment]
GO AHEAD @Rizvi-Faiz
