### ISSUE TITLE
Feature Request: Add Contact Us Page

### ISSUE THREAD

**Issue by Rizvi-Faiz** [jahnvisahni31/DesignDeck#75]
### Feature Request: Add Contact Us Page

**Description:**
We need to add a "Contact Us" page to the website or project. This page will provide users with a way to get in touch with the team for inquiries, support, or feedback.

**Proposed Solution:**
Create a new page with the following sections:
- Contact Form (fields for Name, Email, Message)
- Additional contact information (email address, social media links, etc.)
- A confirmation message upon successful submission of the form
- Error handling for invalid input

**Acceptance Criteria:**
- [ ] Contact form designed with input fields for name, email, and message.
- [ ] Form validation for email and required fields.
- [ ] Success confirmation message after submission.
- [ ] Display of relevant contact information (e.g., support email, social media).
- [ ] Page styled to match the rest of the site and accessible from the navigation or footer.

**Additional Context:**
Include links to social media, support emails, or any other contact channels available. If using a backend service to handle form submissions, mention the integration details.

**Comment by Rizvi-Faiz** [comment]
@jahnvisahni31 please assign to me

**Comment by jahnvisahni31** [comment]
GO AHEAD @Rizvi-Faiz
