### ISSUE TITLE
Updating twitter icons

### ISSUE THREAD

**Issue by ashu273k** [jahnvisahni31/DesignDeck#77]
changing twitter bird icon to X

![image](https://github.com/user-attachments/assets/223f4db8-4e60-481b-86e7-1865bc8544ad)

@jahnvisahni31

**Comment by ashu273k** [comment]
@jahnvisahni31 I would like to work on this issue. Kindly assign it to me.

**Comment by jahnvisahni31** [comment]
GO AHEAD @ashu273k
