### ISSUE TITLE
FAQ content and styling

### ISSUE THREAD

**Issue by saumyayadav25** [jahnvisahni31/DesignDeck#80]
**Is your feature request related to a problem? Please describe.**
In FAQ dark mode, there is not smooth transition when we click on a question.

In light mode, no content is visible at all initially. 
<img width="1376" alt="Screenshot 2024-10-11 at 11 28 40 AM" src="https://github.com/user-attachments/assets/538a2ab7-568a-45cf-a0bd-283c5f0cca88">

Its only visible after clicking on it.
<img width="1220" alt="Screenshot 2024-10-11 at 11 31 14 AM" src="https://github.com/user-attachments/assets/1a3a1341-7334-4703-af08-e33a6bd531a0">

**Describe the solution you'd like**
1) Adding smooth transition to faq when active and closed. 
3) making content visible in light mode.

**Additional context**
Also, the home with blue color does'nt seem good with dark theme or even light theme.  The color can be changed to a better one.

**Comment by saumyayadav25** [comment]
<img width="1390" alt="Screenshot 2024-10-11 at 11 33 57 AM" src="https://github.com/user-attachments/assets/c4292ce9-55dd-441f-9dea-efddf6aed55c">
Also,in the navbar, 
1) the blue color does'nt really match here also. Can implement better styling on it.
2) Nothing is visible inside the blue box, a new user coming to the website will never now that they can switch between light and dark themes. 

Do let me know if i will be assigned any of the tasks

**Comment by jahnvisahni31** [comment]
GO AHEAD @saumyayadav25
