### ISSUE TITLE
URGENT!!!  Error with Liveblocks Authentication: Access Suspended

### ISSUE THREAD

**Issue by jahnvisahni31** [jahnvisahni31/DesignDeck#85]
**Title:**
Implement User Authentication with Liveblocks API in Next.js

**Description:**
The current implementation of the Liveblocks integration lacks proper user authentication and authorization. We need to implement a function, getUserFromDB, that retrieves user information from the database using JWT tokens provided in the request headers. This function should verify the JWT token, fetch user details, and integrate seamlessly with the Liveblocks API for user identification.

Acceptance Criteria:
1. Implement getUserFromDB to extract and verify JWT tokens.
2. Fetch user information from the database based on the decoded token.
3. Update the Liveblocks API handler to utilize the retrieved user information for authentication.
4. Ensure proper error handling and logging.

Please refer to the current integration code for context and any specific user database structure for fetching user details.

**Comment by yashksaini-coder** [comment]
can I work on this issue @jahnvisahni31

**Comment by jahnvisahni31** [comment]
sure you can go ahead

**Comment by jahnvisahni31** [comment]
did you work?

**Comment by jahnvisahni31** [comment]
okay

**Comment by vaibhav-yerkar** [comment]
Hello , can I work on this ?

**Comment by mehul-m-prajapati** [comment]
@jahnvisahni31 : I am having hectic schedule nowadays. You can assign this to someone else.

**Comment by jahnvisahni31** [comment]
okay
