### ISSUE TITLE
Changing Contact Page Appearance according to dark and light modes

### ISSUE THREAD

**Issue by sezallagwal** [jahnvisahni31/DesignDeck#86]
![image](https://github.com/user-attachments/assets/2e94b9ad-ef08-4ee2-a828-c0584b39c2f5)
 Please assign this issue to me @jahnvisahni31

**Comment by jahnvisahni31** [comment]
go ahead with this @sezallagwal

**Comment by Zubaida0113** [comment]
Hey, @jahnvisahni31 can I improve the appearance of the toggle button that enables dark/light mode? 
Replace this :- 
![Screenshot (397)](https://github.com/user-attachments/assets/58564d38-c16d-4d23-81d6-ec6fbd876717)
with something Like this:-

https://github.com/user-attachments/assets/1a710168-6ee3-4c2f-8713-e6e531590e59
