### ISSUE TITLE
Add a mini AI Chat Bot.

### ISSUE THREAD

**Issue by GunaVardhanaReddyT** [jahnvisahni31/DesignDeck#87]
Hey ! Adding a mini AI chatbot to the project can elevate the user experience by providing an in-app ai chat bot.

**Comment by jahnvisahni31** [comment]
go ahead with this @GunaVardhanaReddyT

**Comment by TGEashaan** [comment]
Hey If u don't mind i'd like to try this

**Comment by jahnvisahni31** [comment]
you go ahead will check who gets done first

**Comment by TGEashaan** [comment]
Don't i need to to be assigned in order to do this ?? i mean i am new to open src contribution.

**Comment by jahnvisahni31** [comment]
First you complete the task if you complete the task successful then i assigned this issue to you and merge your pr

**Comment by TGEashaan** [comment]
here we need to utilize the api's like gemini or chatgpt  . so can make a mini chatbot to display on the webpages but in order for functionality . everyone's use you would need to keep api key . no problem right ?
