### ISSUE TITLE
Add the pricing page

### ISSUE THREAD

**Issue by Jay-1409** [jahnvisahni31/DesignDeck#88]
**Is your feature request related to a problem? Please describe.**
Yes, I would like to add the pricing tag

**Describe the solution you'd like**
There will be 3 categories of prices.
- Starter Plan

Price: $15/month
Features:
Access to basic design tools
50 design templates
5 projects per month
Single-user license
Access to free assets (images, fonts)
Basic export options (PNG, JPEG)

- Professional Plan

Price: $49/month
Features:
All Starter features
Unlimited design templates
Unlimited projects
5 team members included
Advanced export options (SVG, PDF)
Custom branding and watermark removal
Access to premium assets (3D models, vectors, stock photos)
Real-time collaboration with team members
Version history for projects

- Enterprise Plan

Price: Custom pricing (contact us)
Features:
All Professional features
Unlimited users
Custom integration with existing tools (Slack, Figma, etc.)
Dedicated account manager
24/7 premium support
Priority access to new features
API access for automation and custom workflows
Custom asset library creation
Training sessions and design consultation for teams

**Comment by jahnvisahni31** [comment]
go ahead with this @Jay-1409

**Comment by jahnvisahni31** [comment]
make something like this basic plan which every user can acces which is free  of cost

**Comment by Jay-1409** [comment]
> make something like this basic plan which every user can acces which is free of cost

okayy on it!!

**Comment by Jay-1409** [comment]
@jahnvisahni31 could you pass this issue to someone better?, i am having lots of issues with using Next.js since i am not very experienced in it unlike in React . Really sorry :( .
