### ISSUE TITLE
Navbar Design Improvement: Add Proper Spacing, Hover Effects, and Animations to Nav Items

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [jahnvisahni31/DesignDeck#89]
# Navbar Design Improvement: Add Proper Spacing, Hover Effects, and Animations to Nav Items

**Summary of the Problem:**
The current navbar design lacks proper spacing between the navigation items, making the navbar look cluttered and less user-friendly. Additionally, there are no hover effects or animations for the nav items, which makes the website feel static and unengaging. Improving the spacing, adding hover effects, and introducing subtle animations would enhance the overall visual appeal and interactivity of the website.

## Expected Behavior
- Navigation items should have sufficient gaps to avoid a cluttered look.
- Hover effects (such as color changes or underlining) should be applied to the nav items for better interactivity.
- Simple animations should be added to nav items for a smoother user experience.
- Proper alignment of nav items should ensure they are well-spaced and consistent throughout the navbar.

## Current Behavior
- The gap between navigation items is minimal, making the navbar look dense and hard to read.
- No hover effects or animations are present, resulting in a static experience.
- Navigation items are not properly aligned, affecting the overall design and aesthetics of the website.

## Steps to Reproduce
1. Open the website and view the navbar at the top.
2. Observe the small gap between the nav items and how closely packed they are.
3. Hover over the nav items and observe the lack of hover effects or animations.
4. Notice the improper alignment and inconsistent spacing between nav items.
 

## Additional Context
Enhancing the navbar design by improving the spacing and adding hover effects will make the website more visually appealing and engaging for users. A well-designed, interactive navbar can significantly improve the user experience by making navigation more intuitive and enjoyable.

## Motivation
By addressing the design and interactivity issues in the navbar, the website will have a more modern and attractive appearance. Properly spaced nav items and hover animations will make the site feel more polished and professional, encouraging users to explore more content.

## Labels
- **Type:** Enhancement
- **Priority:** Medium
- **Status:** Open
- **Area:** UI/UX

## Screenshot
![nav 2](https://github.com/user-attachments/assets/1c3d8598-ac24-4984-a883-02c5f19eff80)

**Comment by jahnvisahni31** [comment]
go ahead @biswajit-sarkar-007
