### ISSUE TITLE
ADD FAQ page

### ISSUE THREAD

**Issue by shubhagarwal1** [jahnvisahni31/DesignDeck#9]
**Describe the solution you'd like**
Implement a dedicated FAQ page that provides users with quick access to common questions and answers. This will help users find solutions to common issues without needing to contact support. The page should be easily accessible from the main navigation menu and be fully responsive for both desktop and mobile devices.

Hey @jahnvisahni31  Please assign this task to me

**Comment by jahnvisahni31** [comment]
please preview this chnges 
![image](https://github.com/user-attachments/assets/23da793a-7a8d-4a4e-8fe7-bc2301205185)

it is not correct it should be one line and i am making .env file please use that key only

**Comment by shubhagarwal1** [comment]
> please preview this chnges ![image](https://private-user-images.githubusercontent.com/121384173/372900650-23da793a-7a8d-4a4e-8fe7-bc2301205185.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4ODEzMDgsIm5iZiI6MTcyNzg4MTAwOCwicGF0aCI6Ii8xMjEzODQxNzMvMzcyOTAwNjUwLTIzZGE3OTNhLTdhOGQtNGE0ZS04ZmU3LWJjMjMwMTIwNTE4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQxNDU2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTljMmM0MDY5MzhiYzZlMzk1NjUwNDZiNjY0MWI4YmE4OTc5NGVlM2E1ZTI2ZWE1YTc0YzYyMjQ1ODk3OWU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.A1OCDZN06AtN4fJGl3DbKDR-L_CSm7SU1tyvPX-eyT8)
> 
> it is not correct it should be one line and and by default when you click on the link it shows the home page by default


see this can be improved in next PR its not like that the whole feature is wrong 
well fine i will make the correction, do you wnat th logo, aciton buttons and the navbar option in one lien or what i am not getting it ?

**Comment by jahnvisahni31** [comment]
yes i want the logo navbar option , action button in 1 line and i have to make sure that the work is done correctly
