### ISSUE TITLE
Footer Design Improvement: Add Hover Effects, Animations, and Proper Spacing for Better User Engagement

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [jahnvisahni31/DesignDeck#90]
# Footer Design Improvement: Add Hover Effects, Animations, and Proper Spacing for Better User Engagement

**Summary of the Problem:**
The footer of the website lacks hover effects and animations, which diminishes the overall interactivity and user engagement. Additionally, the items in the footer are not properly spaced, leading to a cluttered appearance. Improving the footer by adding these elements will enhance the website’s quality and attract more user attention.

## Expected Behavior
- Footer items should have sufficient spacing between them for better readability and a clean layout.
- Adding hover effects (like color changes, underlines, or transitions) will make the footer more interactive.
- Simple animations should be applied to footer items to create a smoother, more engaging user experience.
- The overall alignment of the footer should be improved to ensure consistent spacing and visual appeal.

## Current Behavior
- Footer items are too closely spaced, making the footer look cluttered and hard to navigate.
- There are no hover effects or animations, resulting in a static and unengaging footer.
- The lack of interaction and visual enhancements makes the footer feel less polished and reduces the website's quality.

## Steps to Reproduce
1. Scroll to the bottom of the website and view the footer section.
2. Notice the lack of hover effects and animations when hovering over footer items.
3. Observe the minimal spacing between footer items and the cluttered appearance.

 
## Additional Context
Improving the footer by adding hover effects, animations, and proper spacing will make the website more interactive and visually appealing. This can increase user engagement and enhance the overall quality and professionalism of the website, making it more attractive to visitors.

## Motivation
By addressing the design and interactivity issues in the footer, the website will look more modern and appealing. Well-spaced footer items with hover animations will make the site feel more polished and professional, improving the overall user experience and retaining audience attention.

## Labels
- **Type:** Enhancement
- **Priority:** Medium
- **Status:** Open
- **Area:** UI/UX

## Screenshot

![nav 3](https://github.com/user-attachments/assets/d82ca4fc-c772-49f2-980a-76d2dc21422c)

**Comment by jahnvisahni31** [comment]
go ahead @biswajit-sarkar-007
