### ISSUE TITLE
Hero Section Design Improvement: Enhance Text Styling, Add Animations and Hover Effects, and Style the Button

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [jahnvisahni31/DesignDeck#91]
# Hero Section Design Improvement: Enhance Text Styling, Add Animations and Hover Effects, and Style the Button

**Summary of the Problem:**
The current design of the hero section feels outdated and lacks modern styling elements. The heading text is not styled appropriately, and there are no animations or hover effects, making it less engaging for users. Additionally, the button lacks sufficient styling, such as borders and hover effects, which contributes to the overall outdated appearance. Improving these elements will enhance the visual appeal and user experience of the website.

## Expected Behavior
- The heading text should have a modern font style, appropriate sizing, and color contrast to grab attention.
- Add animations to the heading text for a dynamic entrance effect when the page loads.
- Implement hover effects on the heading text to enhance interactivity.
- The button should have a well-defined style with borders, color contrast, and padding to make it more visually appealing.
- Introduce hover effects on the button (such as color changes or subtle scaling) to improve user interaction.

## Current Behavior
- The heading text appears plain and lacks modern styling.
- No animations or hover effects are present, resulting in a static hero section.
- The button looks unstyled and does not stand out, lacking borders or visual interest.
- Overall, the hero section does not effectively capture user attention and feels outdated.

## Steps to Reproduce
1. Open the website and view the hero section at the top of the page.
2. Observe the lack of styling on the heading text and how it appears outdated.
3. Notice the absence of animations and hover effects on both the heading text and the button.
4. Check the button's styling and observe how it blends into the background without visual emphasis.

 

## Additional Context
Improving the design of the hero section will significantly enhance the website's overall visual appeal and user experience. A modernized hero section with well-styled text and buttons can capture user attention more effectively and encourage them to engage with the website's content.

## Motivation
By addressing the design issues in the hero section, the website will have a more contemporary and attractive appearance. Enhanced text styling, animations, and button interactions will create a polished and professional look that draws users in and encourages them to explore further.

## Labels
- **Type:** Enhancement
- **Priority:** Medium
- **Status:** Open
- **Area:** UI/UX

## Screenshot
![hero](https://github.com/user-attachments/assets/709e04b4-22b0-452a-8c7a-688cd3899931)

**Comment by jahnvisahni31** [comment]
i guess someone is working on this
