### ISSUE TITLE
[FEATURE REQUEST] Implement Theme Support for Header and Footer Components

### ISSUE THREAD

**Issue by sezallagwal** [jahnvisahni31/DesignDeck#93]
Currently, the header and footer components do not adapt to the theme toggles (light and dark modes). This lack of consistency can lead to a disjointed user experience as users switch between themes. @jahnvisahni31 

I plan to implement the following steps to achieve this:

1. Access Current Theme: Use the useTheme hook from next-themes in the header and footer components to determine the current theme.
2. Conditional Styling: Apply conditional classes or styles in the header and footer based on the current theme.
3. Testing: Ensure that the changes are responsive and work seamlessly when the theme is toggled.

**Comment by jahnvisahni31** [comment]
i guess someone is working @
