### ISSUE TITLE
Improve navbar of the website for different screen size by adding a hamburger symbol.

### ISSUE THREAD

**Issue by Zubaida0113** [jahnvisahni31/DesignDeck#95]
**Describe the bug**
The navigation bar does not adjust optimally for different screen sizes, causing layout issues on smaller devices. A hamburger menu is needed for better responsiveness and user experience on mobile screens.

**To Reproduce**
1.Go to the website on a smaller screen or resize your browser window.
2.Observe how the navbar does not adapt or becomes cluttered.
3.Attempt to click on menu items or resize further.
4.Notice that the navigation menu becomes difficult to interact with or is not visible.

**Expected behavior**
The navbar should dynamically adjust to smaller screens by replacing the standard menu with a hamburger icon. When clicked, the icon should expand to display the navigation options.

**Screenshots**
![Screenshot (394)](https://github.com/user-attachments/assets/720df76a-c0b1-4099-8edd-89336843200d)

**Desktop (please complete the following information):**
 - OS:  Windows
 - Browser:  chrome
 - Version : 129.0.6668.100 

**Smartphone (please complete the following information):**
 - Device: Samsung A51
 - Browser - Chrome
 - Version- 129.0.6668.100 
 So I would like to work on this issue.

**Comment by jahnvisahni31** [comment]
Go ahead with this
