### ISSUE TITLE
[Feature Enhancement] Totally Changing the UI of Contact Us page to match the UI of the site ✨

### ISSUE THREAD

**Issue by VRtheKing** [jahnvisahni31/DesignDeck#97]
Hii @jahnvisahni31 I wish to totally redesign the UI of our contact page to match the UI of the site, so please assign me this issue under gssoc-ext and hactoberfest level1 so that i can start working immediately.

**Comment by jahnvisahni31** [comment]
Sure go ahead @VRtheKing
